"""make user email unique

Revision ID: 5eb778fce96c
Revises: c4966764b940
Create Date: 2022-10-23 11:25:09.082490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5eb778fce96c'
down_revision = 'c4966764b940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.create_unique_constraint('email', 'user', ['email'])
    op.drop_column('user', 'user_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_status', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('email', 'user', type_='unique')
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    # ### end Alembic commands ###
