"""remove artist last_name

Revision ID: bec87187ef99
Revises: 5eb778fce96c
Create Date: 2022-10-23 12:00:16.063882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bec87187ef99'
down_revision = '5eb778fce96c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('name', sa.String(length=25), nullable=False))
    op.drop_column('artist', 'last_name')
    op.drop_column('artist', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('first_name', mysql.VARCHAR(length=25), nullable=False))
    op.add_column('artist', sa.Column('last_name', mysql.VARCHAR(length=25), nullable=False))
    op.drop_column('artist', 'name')
    # ### end Alembic commands ###
